FROM postgres:alpine3.19
EXPOSE 5432
COPY ./pg_hba.conf /etc/postgresql/15/main/pg_hba.conf
COPY ./setup.sql /docker-entrypoint-initdb.d/setup.sql
# COPY ./setup_db.sh /docker-entrypoint-initdb.d/setup_db.sh
CMD ["postgres"]