# Generated by Django 5.0.4 on 2024-06-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('p1', models.PositiveIntegerField(null=True)),
                ('p2', models.PositiveIntegerField(null=True)),
                ('p3', models.PositiveIntegerField(null=True)),
                ('p4', models.PositiveIntegerField(null=True)),
                ('in_game', models.BooleanField(default=False)),
                ('mtt', models.BooleanField(default=False)),
                ('max_users', models.PositiveIntegerField(default=2)),
                ('cur_users', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
