# Generated by Django 5.0.4 on 2024-05-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='gost',
            new_name='host',
        ),
    ]
