#!/bin/sh

set -e

psql -U $POSTGRES_USER << EOF
create database $USERDATA_DB_NAME;
create user $USERDATA_DB_USER with password '$USERDATA_DB_PW';
ALTER DATABASE $USERDATA_DB_NAME OWNER TO $USERDATA_DB_USER;
GRANT ALL ON DATABASE $USERDATA_DB_NAME TO $USERDATA_DB_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $USERDATA_DB_USER;
EOF