# Generated by Django 5.0.4 on 2024-06-17 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('introduce', models.CharField(max_length=200)),
                ('email', models.EmailField(default='example@student.42seoul.kr', max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.jpg', upload_to='avatars/')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('exp', models.PositiveBigIntegerField(default=0)),
                ('friends', models.ManyToManyField(blank=True, related_name='friend_set', related_query_name='friend', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_score', models.PositiveIntegerField()),
                ('p2_score', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to=settings.AUTH_USER_MODEL)),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['p1'], name='api_matchhi_p1_id_10dd21_idx'), models.Index(fields=['p2'], name='api_matchhi_p2_id_e8a8bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='api_otpmode_user_id_44a8cd_idx')],
            },
        ),
    ]
