# Generated by Django 5.0.4 on 2024-06-20 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(default='', max_length=50)),
                ('introduce', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='example@student.42seoul.kr', max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.jpg', upload_to='avatars/')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('exp', models.PositiveBigIntegerField(default=0)),
                ('online', models.BooleanField(default=False)),
                ('friends', models.ManyToManyField(blank=True, related_name='friend_set', related_query_name='friend', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
